title: Do Fireballers Make Better Relievers?
description: An exploratory study on whether a pitchers fastball velocity makes them a more effective reliever in high leverage situations.
theme: jekyll-theme-minimal
